apiVersion: v1
kind: Deployment
metadata:
  name: whatsapp
  labels: { app: whatsapp }
spec:
  replicas: 1
  template:
    metadata: { labels: { app: whatsapp } }
    spec:
      containers:
        - name: whatsapp
          image: ?/whatsapp:${TAG}
          command:
          ports:
            - containerPort: 8080
          # volumeMounts:
          #   - name: news-config
          #     mountPath: /etc/news/
          #     readOnly: true
      # volumes:
      #   - name: news-config
      #     configMap: { name: news-config }
